### ISSUE TITLE
Update the navbar closing issue on mobile device

### ISSUE THREAD

**Issue by mdmarufsarker** [mdmarufsarker/anisul-islam#6]
1. When a user press on a nav item then the navigation bar  will automatically be closed
2. Update the image size (device resolution: 300-450px)
3. Use text align left not justify

Create a new branch using your username then send a pull request :1st_place_medal:

**Comment by mdmarufsarker** [comment]
@alnahian2003  did you solve the problem?

**Comment by alnahian2003** [comment]
I think that should do it. Btw I apologise for not working on the issue on time for some personal issues here. But you already fixed it, bravo!

You can now close this issue. Good luck

**Comment by mdmarufsarker** [comment]
Thanks for participating with me and good luck dude.
